### ISSUE TITLE
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lnetpbm

### ISSUE THREAD

**Issue by 3togo** [ctrlesc/ffmpeg-cxc-build#2]
when I run
64
 2061  ROOT_PATH=~/ SRC_PATH=src HINTS_FILE=/dev/null CXC_FETCH_ONLY=1 ./ffmpeg-cxc-mingw64
./ffmepg-cxc-mingw64
I got the following error. 
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lnetpbm
How to fix it?

**Comment by ctrlesc** [comment]
What is your build environment and which library is it trying to configure when you get the error?

**Comment by ctrlesc** [comment]
Closed due to lack of response.
