### ISSUE TITLE
Feature Request: SVT-AV1

### ISSUE THREAD

**Issue by alex9434** [ctrlesc/ffmpeg-cxc-build#3]
Dear @ctrlesc,

very helpful script to cross-compile ffmpeg. Are you planning on integrating SVT-AV1? It's a faster version of the AV1 coded from Intel.

https://github.com/AOMediaCodec/SVT-AV1

Thank you,
Alex

**Comment by ctrlesc** [comment]
I will take a look.

**Comment by ctrlesc** [comment]
Give 856499a12e6b3ccfef29f692b6b12f4e50e4e676 a try.

**Comment by alex9434** [comment]
Excellent, will do tomorrow and report back! Thank you

**Comment by alex9434** [comment]
Hi @ctrlesc, I successfully compiled ffmpeg with SVT-AV1 enabled. Thank you!

**Comment by ctrlesc** [comment]
Glad to hear and thanks for testing.
