### ISSUE TITLE
Script build error

### ISSUE THREAD

**Issue by 0Ky** [ctrlesc/ffmpeg-cxc-build#4]
I get the following error `ERROR: srt >= 1.3.0 not found using pkg-config` when compiling FFmpeg Latest Build, Ubuntu 22.04 (WSL)

```
====> ffmpeg <====
Cloning into 'ffmpeg'...
remote: Enumerating objects: 7601, done.
remote: Counting objects: 100% (7601/7601), done.
remote: Compressing objects: 100% (5846/5846), done.
Receiving objects: 100% (695665/695665), 168.25 MiB | 5.40 MiB/s, done.
remote: Total 695665 (delta 5420), reused 2142 (delta 1704)
Resolving deltas: 100% (562611/562611), done.
====> ffmpeg: fetch success -> git https://git.ffmpeg.org/ffmpeg.git  <====
ERROR: srt >= 1.3.0 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
====> ffmpeg-cxc-mingw64: configure stage failed -> ffmpeg <====
```

**Comment by 0Ky** [comment]
I've made changes to `#libsrt` in the [`ffmpeg-cxc-mingw64`](https://github.com/ctrlesc/ffmpeg-cxc-build/blob/a62ad14/ffmpeg-cxc-mingw64#L1114C9-L1114C54) file:

- Modified `-DCMAKE_INSTALL_PREFIX="$ROOT_PATH/$OUT_PATH"` to `-DCMAKE_INSTALL_PREFIX="$ROOT_PATH"`
- Added `-DCMAKE_INSTALL_LIBDIR="$ROOT_PATH/$OUT_PATH/lib"`

This is got rid of the `ERROR: srt >= 1.3.0 not found using pkg-config` error in Ubuntu 22.04 using WSL environment.

**Comment by ctrlesc** [comment]
Does it build if you follow the **Example Build Procedure** from the readme?  Also, I think you are building latest without having a local copy of the repositories - not a requirement, but much faster to build and keep up to date. If you have some time, please follow the **Example Build Procedure** . This will create a local copy of the repositories at \~/src , and you will need to copy and edit ffmpeg-cxc-build-hints removing the leading # symbol from the lines which look like -> #amf	url	file://~/src/amf . Let me know the results. We can dial in the latest build after that.
