### ISSUE TITLE
Error with SDL

### ISSUE THREAD

**Issue by alex9434** [ctrlesc/ffmpeg-cxc-build#5]
Hi, 
Unfortunately I get an error message with ffmpeg-native:

`
====> sdl <====
Cloning into 'sdl'...
remote: Enumerating objects: 125749, done.
remote: Counting objects: 100% (12568/12568), done.
remote: Compressing objects: 100% (934/934), done.
remote: Total 125749 (delta 11825), reused 12045 (delta 11591), pack-reused 113181
Receiving objects: 100% (125749/125749), 102.66 MiB | 12.30 MiB/s, done.
Resolving deltas: 100% (97915/97915), done.
====> sdl: fetch success -> git https://github.com/libsdl-org/SDL.git  <====
/home/alex/ffmpeg-cxc-build/ffmpeg-native: line 962: ./configure: No such file or directory
====> ffmpeg-native: configure stage failed -> sdl <====

`

I am trying to build ffmpeg to run on Debian.

**Comment by ctrlesc** [comment]
Try this for a command line:
`HINTS_FILE=/home/alex/ffmpeg-cxc-build/ffmpeg-native-build-hints ffmpeg-native`

SDL requires a specific branch to build correctly. The one specified in the hints file above includes it. Please give it a try.
