### ISSUE TITLE
Support this video fiilter ?

### ISSUE THREAD

**Issue by Usulyre** [ctrlesc/ffmpeg-cxc-build#6]
Hi,

I have been unable to cross-compile this particular build of ffmpeg with a particular filter. Can you try this? I would like to use it on windows os. Thanks in advance.

https://github.com/mpv-player/mpv/issues/11060

https://github.com/philipl/FFmpeg/tree/nvoffruc

**Comment by ctrlesc** [comment]
It looks like you might want to look at the patch here [https://github.com/EionRobb/FFmpeg/tree/patch-1](url) which appears to address what you are asking for.

Your request is for a custom patch which is beyond what I am trying to maintain.  This project is more of a build script facilitating compilation using mostly official repositories.
